# образ для vue: https://hub.docker.com/r/vuejs/ci
# образ для питона: python:3.7
# надо внутри каждого образа настроить установку зависимостей (я установлю только зависимости backend)

# FROM python:3.7

# fix problem with timezon
# ENV TZ=Europe/Moscow
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# clone repository (add later)

# download dependencies for backend
# RUN apt-get update && apt-get upgrade -y
# RUN pip3 install torch==1.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
# RUN pip3 install transformers django djangorestframework 

# start container in compiled library
# WORKDIR ~/PatternsCollection
